[package]
name = "rusthll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 

[dependencies]
fasthash = "0.4.0"
sha256 = "1.1.3"
hex = "0.4.3"
byteorder = "1.4.3"
